import Head from 'next/head'
import Image from 'next/image'
import fetchSheet from '../components/fetchSheet'
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     {fetchSheet()}
    </div>
  )
}
